#ifdef INV_USE_LEGACY_NAMES
#ifndef INV_INV_LEGACY_H__
#define INV_INV_LEGACY_H__
#define MLSerialOpen inv_serial_start
#define MLSerialClose inv_serial_stop
#define MLSetMPUSensors inv_set_mpu_sensors
#define MLSerialGetHandle inv_get_serial_handle
#define MLUpdateData inv_update_data
#define MLCheckFlag inv_check_flag
#define MLSetBiasUpdateFunc inv_set_bias_update
#define MLTurnOnBiasFromNoMotion inv_turn_on_bias_from_no_motion
#define MLTurnOffBiasFromNoMotion inv_turn_off_bias_from_no_motion
#define MLSetMantis inv_set_mpu_6050_config
#define MLGetArray inv_get_array
#define MLGetFloatArray inv_get_float_array
#define MLSetArray inv_set_array
#define MLSetFloatArray inv_set_float_array
#define MLApplyAccelEndian inv_apply_endian_accel
#define MLApplyCalibration inv_apply_calibration
#define MLSetGyroCalibration inv_set_gyro_calibration
#define MLSetAccelCalibration inv_set_accel_calibration
#define MLSetMagCalibration inv_set_compass_calibration
#define MLSetMotionCallback inv_set_motion_callback
#define MLGetMotionState inv_get_motion_state
#define MLVersion inv_get_version
#define MLSetMotionInterrupt inv_set_motion_interrupt
#define MLSetFifoInterrupt inv_set_fifo_interrupt
#define MLGetInterrupts inv_get_interrupts
#define MLGetGyroPresent inv_get_gyro_present 
#define MLSetNoMotionTime inv_set_no_motion_time
#define MLSetNoMotionThresh inv_set_no_motion_thresh
#define MLSetNoMotionThreshAccel inv_set_accel_no_motion_thresh
#define MLResetMotion inv_reset_motion
#define MLUpdateBias inv_update_bias
#define MLSetDeadZone inv_set_dead_zone
#define MLBiasStart inv_start_bias_calc
#define MLBiasStop inv_stop_bias_calc
#define MLXInit inv_init_ml
#define RegisterProcessDmpInterrupt inv_register_dmp_interupt_cb
#define UnRegisterProcessDmpInterrupt inv_unregister_dmp_interupt_cb
#define RunProcessDmpInterruptFuncs inv_run_dmp_interupt_cb
#define MLSetModeChangeCB inv_set_mode_change

// Define remapping
#define ML_VERSION                     INV_VERSION  
#define ML_VERSION_MAJOR               INV_VERSION_MAJOR             
#define ML_VERSION_MINOR               INV_VERSION_MINOR             
#define ML_VERSION_SUB_MINOR           INV_VERSION_SUB_MINOR         
#define ML_VERSION_MAJOR_STR           INV_VERSION_MAJOR_STR         
#define ML_VERSION_MINOR_STR           INV_VERSION_MINOR_STR         
#define ML_VERSION_SUB_MINOR_STR       INV_VERSION_SUB_MINOR_STR     
#define ML_VERSION_NONE                INV_VERSION_NONE              
#define ML_VERSION_PROTOTYPE           INV_VERSION_PROTOTYPE         
#define ML_VERSION_ENGINEERING         INV_VERSION_ENGINEERING       
#define ML_VERSION_PRE_ALPHA           INV_VERSION_PRE_ALPHA         
#define ML_VERSION_ALPHA               INV_VERSION_ALPHA             
#define ML_VERSION_BETA                INV_VERSION_BETA              
#define ML_VERSION_PRODUCTION          INV_VERSION_PRODUCTION        
#define ML_VERSION_TYPE                INV_VERSION_TYPE
#define ML_MOTION_DETECT               INV_MOTION_DETECT              
#define ML_BIAS_UPDATE                 INV_BIAS_UPDATE                
#define ML_GESTURE                     INV_GESTURE                    
#define ML_CONTROL                     INV_CONTROL                    
#define ML_ORIENTATION                 INV_ORIENTATION                
#define ML_PEDOMETER                   INV_PEDOMETER                  
#define ML_BASIC                       INV_BASIC                      
#define ML_DATA_FIFO                   INV_DATA_FIFO                  
#define ML_DATA_POLL                   INV_DATA_POLL                  
#define ML_INT_MOTION                  INV_INT_MOTION                 
#define ML_INT_FIFO                    INV_INT_FIFO                   
#define ML_INT_TAP                     INV_INT_TAP                    
#define ML_INT_ORIENTATION             INV_INT_ORIENTATION            
#define ML_INT_SHAKE_PITCH             INV_INT_SHAKE_PITCH            
#define ML_INT_SHAKE_ROLL              INV_INT_SHAKE_ROLL             
#define ML_INT_SHAKE_YAW               INV_INT_SHAKE_YAW              
#define ML_BIAS_FROM_NO_MOTION         INV_BIAS_FROM_NO_MOTION        
#define ML_BIAS_FROM_GRAVITY           INV_BIAS_FROM_GRAVITY          
#define ML_BIAS_FROM_TEMPERATURE       INV_BIAS_FROM_TEMPERATURE      
#define ML_BIAS_FROM_LPF               INV_BIAS_FROM_LPF              
#define ML_MAG_BIAS_FROM_MOTION        INV_MAG_BIAS_FROM_MOTION       
#define ML_MAG_BIAS_FROM_GYRO          INV_MAG_BIAS_FROM_GYRO         
#define ML_LEARN_BIAS_FROM_TEMPERATURE INV_LEARN_BIAS_FROM_TEMPERATURE
#define ML_AUTO_RESET_MAG_BIAS         INV_AUTO_RESET_MAG_BIAS        
#define ML_REJECT_MAG_DISTURBANCE      INV_REJECT_MAG_DISTURBANCE     
#define ML_PROGRESSIVE_NO_MOTION       INV_PROGRESSIVE_NO_MOTION      
#define ML_BIAS_FROM_FAST_NO_MOTION    INV_BIAS_FROM_FAST_NO_MOTION   
#define ML_X_AXIS                      INV_X_AXIS                     
#define ML_Y_AXIS                      INV_Y_AXIS                     
#define ML_Z_AXIS                      INV_Z_AXIS                     
#define ML_PITCH                       INV_PITCH                      
#define ML_ROLL                        INV_ROLL                       
#define ML_YAW                         INV_YAW                        
#define ML_GYROS                       INV_GYROS                      
#define ML_ACCELS                      INV_ACCELS                     
#define ML_ROTATION_MATRIX             INV_ROTATION_MATRIX            
#define ML_QUATERNION                  INV_QUATERNION                 
#define ML_EULER_ANGLES                INV_EULER_ANGLES               
#define ML_LINEAR_ACCELERATION         INV_LINEAR_ACCELERATION        
#define ML_LINEAR_ACCELERATION_WORLD   INV_LINEAR_ACCELERATION_WORLD  
#define ML_GRAVITY                     INV_GRAVITY                    
#define ML_ANGULAR_VELOCITY            INV_ANGULAR_VELOCITY           
#define ML_GYRO_CALIBRATION_MATRIX     INV_GYRO_CALIBRATION_MATRIX    
#define ML_ACCEL_CALIBRATION_MATRIX    INV_ACCEL_CALIBRATION_MATRIX   
#define ML_GYRO_BIAS                   INV_GYRO_BIAS                  
#define ML_ACCEL_BIAS                  INV_ACCEL_BIAS                 
#define ML_GYRO_TEMP_SLOPE             INV_GYRO_TEMP_SLOPE            
#define ML_RAW_DATA                    INV_RAW_DATA                   
#define ML_DMP_TAP                     INV_DMP_TAP                    
#define ML_DMP_TAP2                    INV_DMP_TAP2                   
#define ML_EULER_ANGLES_X              INV_EULER_ANGLES_X             
#define ML_EULER_ANGLES_Y              INV_EULER_ANGLES_Y             
#define ML_EULER_ANGLES_Z              INV_EULER_ANGLES_Z             
#define ML_BIAS_UNCERTAINTY            INV_BIAS_UNCERTAINTY           
#define ML_DMP_PACKET_NUMBER           INV_DMP_PACKET_NUMBER          
#define ML_FOOTER                      INV_FOOTER                     
#define ML_CONTROL_DATA                INV_CONTROL_DATA               
#define ML_MAGNETOMETER                INV_MAGNETOMETER               
#define ML_PEDLBS                      INV_PEDLBS                     
#define ML_MAG_RAW_DATA                INV_MAG_RAW_DATA               
#define ML_MAG_CALIBRATION_MATRIX      INV_MAG_CALIBRATION_MATRIX     
#define ML_MAG_BIAS                    INV_MAG_BIAS                   
#define ML_HEADING                     INV_HEADING                    
#define ML_MAG_BIAS_ERROR              INV_MAG_BIAS_ERROR             
#define ML_PRESSURE                    INV_PRESSURE                   
#define ML_LOCAL_FIELD                 INV_LOCAL_FIELD                
#define ML_MAG_SCALE                   INV_MAG_SCALE                  
#define ML_RELATIVE_QUATERNION         INV_RELATIVE_QUATERNION        
#define ML_NO_RESET                    INV_NO_RESET                   
#define ML_RESET                       INV_RESET                      
#define ML_MOTION                      INV_MOTION                     
#define ML_NO_MOTION                   INV_NO_MOTION                 
#define ML_STATE_IDLE                  INV_STATE_IDLE                
#define ML_STATE_RUNNING               INV_STATE_RUNNING             
#define ML_RAW_DATA_READY              INV_RAW_DATA_READY            
#define ML_PROCESSED_DATA_READY        INV_PROCESSED_DATA_READY      
#define ML_GOT_GESTURE                 INV_GOT_GESTURE               
#define ML_MOTION_STATE_CHANGE         INV_MOTION_STATE_CHANGE       
#define ML_NONE                        INV_NONE                      
#define ML_INVALID_FIFO_RATE           INV_INVALID_FIFO_RATE         
#define ML_BIAS_UPDATE_FUNC_DEFAULT    INV_BIAS_UPDATE_FUNC_DEFAULT  
#define ML_ORIENTATION_MASK_DEFAULT    INV_ORIENTATION_MASK_DEFAULT  
#define ML_PROCESSED_DATA_CALLBACK_DEFAULT   INV_PROCESSED_DATA_CALLBACK_DEFAULT      
#define ML_ORIENTATION_CALLBACK_DEFAULT INV_ORIENTATION_CALLBACK_DEFAULT         
#define ML_MOTION_CALLBACK_DEFAULT     INV_MOTION_CALLBACK_DEFAULT              
#define ML_PRIORITY_BUS_ACCEL          INV_PRIORITY_BUS_ACCEL           
#define ML_PRIORITY_EXTERNAL_SLAVE_MAG INV_PRIORITY_EXTERNAL_SLAVE_MAG  
#define ML_PRIORITY_FAST_NO_MOTION     INV_PRIORITY_FAST_NO_MOTION      
#define ML_PRIORITY_BIAS_NO_MOTION     INV_PRIORITY_BIAS_NO_MOTION      
#define ML_PRIORITY_TEMP_COMP          INV_PRIORITY_TEMP_COMP           
#define ML_PRIORITY_CONTROL            INV_PRIORITY_CONTROL             
#define ML_PRIORITY_EIS                INV_PRIORITY_EIS                 
#define ML_PRIORITY_ORIENTATION        INV_PRIORITY_ORIENTATION         
#define ML_PRIORITY_PEDOMETER_FULLPOWER INV_PRIORITY_PEDOMETER_FULLPOWER 
#define ML_PRIORITY_NAVIGATION_PEDOMETER INV_PRIORITY_NAVIGATION_PEDOMETER
#define ML_PRIORITY_GESTURE            INV_PRIORITY_GESTURE             
#define ML_PRIORITY_GLYPH              INV_PRIORITY_GLYPH               
#define ML_PRIORITY_SET_GYRO_BIASES    INV_PRIORITY_SET_GYRO_BIASES     
#define ML_MAX_NUM_ACCEL_SAMPLES       INV_MAX_NUM_ACCEL_SAMPLES
#define ML_ELEMENT_1                   INV_ELEMENT_1            
#define ML_ELEMENT_2                   INV_ELEMENT_2            
#define ML_ELEMENT_3                   INV_ELEMENT_3            
#define ML_ELEMENT_4                   INV_ELEMENT_4            
#define ML_ELEMENT_5                   INV_ELEMENT_5            
#define ML_ELEMENT_6                   INV_ELEMENT_6            
#define ML_ELEMENT_7                   INV_ELEMENT_7            
#define ML_ELEMENT_8                   INV_ELEMENT_8            
#define ML_ALL                         INV_ALL                  
#define ML_ELEMENT_MASK                INV_ELEMENT_MASK         
#define ML_16_BIT                      INV_16_BIT               
#define ML_32_BIT                      INV_32_BIT               
#define ML_ACCURACY_MASK               INV_ACCURACY_MASK        
#define ML_GYRO_FROM_RAW               INV_GYRO_FROM_RAW        
#define ML_GYRO_FROM_QUATERNION        INV_GYRO_FROM_QUATERNION 
#define ML_SGB_NO_MOTION               INV_SGB_NO_MOTION 
#define ML_SGB_FAST_NO_MOTION          INV_SGB_FAST_NO_MOTION
#define ML_SGB_TEMP_COMP               INV_SGB_TEMP_COMP 
#define ML_CAL_ACCEL_LEN               INV_CAL_ACCEL_LEN 
#define ML_CAL_COMPASS_LEN             INV_CAL_COMPASS_LEN
#define ML_CAL_HDR_LEN                 INV_CAL_HDR_LEN    
#define ML_CAL_CHK_LEN                 INV_CAL_CHK_LEN    
#define ML_CONTROL_1                   INV_CONTROL_1      
#define ML_CONTROL_2                   INV_CONTROL_2      
#define ML_CONTROL_3                   INV_CONTROL_3      
#define ML_CONTROL_4                   INV_CONTROL_4      
#define ML_GRID                        INV_GRID           
#define ML_SMOOTH                      INV_SMOOTH         
#define ML_DEAD_ZONE                   INV_DEAD_ZONE      
#define ML_HYSTERESIS                  INV_HYSTERESIS     
#define ML_NO_RESET                    INV_NO_RESET       
#define ML_RESET                       INV_RESET          
#define ML_CTRL_SIGNAL                 INV_CTRL_SIGNAL    
#define ML_CTRL_GRID_NUM               INV_CTRL_GRID_NUM  
#define ML_CTRL_PITCH                  INV_CTRL_PITCH     
#define ML_CTRL_ROLL                   INV_CTRL_ROLL      
#define ML_CTRL_YAW                    INV_CTRL_YAW       
#define ML_X_GYRO            	 INV_X_GYRO		
#define ML_Y_GYRO	       	 INV_Y_GYRO		
#define ML_Z_GYRO		 INV_Z_GYRO		
#define ML_DMP_PROCESSOR	 INV_DMP_PROCESSOR	
#define ML_X_ACCEL		 INV_X_ACCEL		
#define ML_Y_ACCEL		 INV_Y_ACCEL		
#define ML_Z_ACCEL		 INV_Z_ACCEL		
#define ML_X_COMPASS		 INV_X_COMPASS		
#define ML_Y_COMPASS		 INV_Y_COMPASS		
#define ML_Z_COMPASS		 INV_Z_COMPASS		
#define ML_X_PRESSURE		 INV_X_PRESSURE		
#define ML_Y_PRESSURE		 INV_Y_PRESSURE		
#define ML_Z_PRESSURE		 INV_Z_PRESSURE		
#define ML_TEMPERATURE		 INV_TEMPERATURE		
#define ML_TIME			 INV_TIME			
#define ML_THREE_AXIS_GYRO	 INV_THREE_AXIS_GYRO	
#define ML_THREE_AXIS_ACCEL	 INV_THREE_AXIS_ACCEL	
#define ML_THREE_AXIS_COMPASS	 INV_THREE_AXIS_COMPASS	
#define ML_THREE_AXIS_PRESSURE	 INV_THREE_AXIS_PRESSURE	
#define ML_FIVE_AXIS		 INV_FIVE_AXIS		
#define ML_SIX_AXIS_GYRO_ACCEL	 INV_SIX_AXIS_GYRO_ACCEL	
#define ML_SIX_AXIS_ACCEL_COMPASS INV_SIX_AXIS_ACCEL_COMPASS
#define ML_NINE_AXIS		 INV_NINE_AXIS			
#define ML_ALL_SENSORS		 INV_ALL_SENSORS			
#define ML_STATE_SERIAL_CLOSED     INV_STATE_SERIAL_CLOSED    
#define ML_STATE_SERIAL_OPENED     INV_STATE_SERIAL_OPENED    
#define ML_STATE_DMP_OPENED        INV_STATE_DMP_OPENED       
#define ML_STATE_DMP_STARTED       INV_STATE_DMP_STARTED      
#define ML_STATE_DMP_STOPPED       INV_STATE_DMP_STOPPED      
#define ML_STATE_DMP_CLOSED        INV_STATE_DMP_CLOSED       
#define ML_STATE_NAME              INV_STATE_NAME          
#define ML_DMPDEFAULT_H__e INV_DMPDEFAULT_H__
#define ML_H INV_H
#define ML_INCLUDE_H__ INV_INCLUDE_H__
#define INV_ML_LEGACY_H__ INV_INV_LEGACY_H__
#define _ML_MPUTEST_H_ _INV_MPUTEST_H_
#define INV_ML_MPU_TEST_LEGACY_H__ INV_INV_MPU_TEST_LEGACY_H__
#define ML_STORED_DATA_H INV_STORED_DATA_H
#define INVENSENSE_ML_FIFO_HW_H__ INVENSENSE_INV_FIFO_HW_H__
#define INVENSENSE_ML_FIFO_HW_LEGACY_H__ INVENSENSE_INV_FIFO_HW_LEGACY_H__
#define INVENSENSE_ML_MATH_FUNC_H__ INVENSENSE_INV_MATH_FUNC_H__
#define INV_ML_MATH_FUNC_LEGACY_H__ INV_INV_MATH_FUNC_LEGACY_H__
#define ML_SET_GYRO_BIAS__H__ INV_SET_GYRO_BIAS__H__
#define ML_BIAS_NO_MOTION_H__ INV_BIAS_NO_MOTION_H__
#define INVENSENSE_ML_FIFO_H__ INVENSENSE_INV_FIFO_H__

#endif
#endif
