#ifdef INV_USE_LEGACY_NAMES
#ifndef INV_INV_MPU_TEST_LEGACY_H__
#define INV_INV_MPU_TEST_LEGACY_H__

#define MLSelfTestFactoryCalibrate inv_self_test_factory_calibrate
#define MLSelfTestSetAccelZOrient inv_self_test_accel_z_orient
#define MLSelfTestRun inv_run_self_test
#define MLSelfTestBiasOnly inv_self_test_bias_only
#define TestSetParameters inv_set_self_test_parameters

#endif
#endif
