#ifndef __CONFIG_H__
#define __CONFIG_H__

#define ENABLE_AUTO_SWITCH 1
#define ENABLE_SWITCH_FRAMEBUFFER 1
#define DISPLAY_UNTIL_WAKEUP 0
#define ENABLE_OTG_MANAGER 0

#ifdef DISPLAY_POLICY_BOX
#define DEFALUT_SCREEN_SCALE 95
#else
#define DEFALUT_SCREEN_SCALE 100
#endif

#endif /*__CONFIG_H__*/
