
LOCAL_PATH:= $(call my-dir)

SMARTCOMPASS_LIB=libSmartCompass

include $(CLEAR_VARS)
LOCAL_C_INCLUDES := \
	$(KERNEL_HEADERS) \
	$(LOCAL_PATH)/$(SMARTCOMPASS_LIB)

LOCAL_SRC_FILES:= \
	AKMD_Driver.c \
	DispMessage.c \
	FileIO.c \
	Measure.c \
	main.c \
	misc.c \
	Acc_mma8452.c


LOCAL_MODULE  := akmd
LOCAL_SRC_FILES += FST_AK09911.c
LOCAL_CFLAGS  += -DAKMD_FOR_AK09911
LOCAL_LDFLAGS += -L$(LOCAL_PATH)/$(SMARTCOMPASS_LIB) -lAK09911


LOCAL_CFLAGS += -Wall -Wextra
#LOCAL_CFLAGS += -DENABLE_AKMDEBUG=1
#LOCAL_CFLAGS += -DAKM_LOG_ENABLE

LOCAL_MODULE_TAGS := optional
LOCAL_FORCE_STATIC_EXECUTABLE := false
LOCAL_STATIC_LIBRARIES :=
LOCAL_SHARED_LIBRARIES := libc libm libutils libcutils
include $(BUILD_EXECUTABLE)



